version: 2
updates:
  - package-ecosystem: "nix"
    directory: "/" # Location of the Nix expressions
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
